name: choice_puzzle_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^6.0.0
  go_router: ^7.1.1
  logging: ^1.2.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
#  carousel_slider: ^4.2.1
#  google_mobile_ads: ^3.0.0  # Ads
  flame: ^1.26.0
  flame_audio: ^2.10.2
  infinite_scroll_pagination: ^4.0.0
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.2
#  flutter_image_compress: ^2.0.3
  flutter_screenutil: ^5.9.3
  card_swiper: ^2.0.4
  awesome_dialog: ^3.2.1
  lottie: ^2.7.0
  mime: ^1.0.5
  cherry_toast: ^1.10.1
  flutter_easyloading: ^3.0.5
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.0
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.3
  image_picker: ^1.1.2
  file_picker: ^9.2.0
#  mixpanel_flutter: ^2.0.0

dev_dependencies:
#  analysis_defaults:
#    path: ../analysis_defaults
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.0
  test: ^1.19.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/music/
    - assets/sfx/
    - assets/lottie/
    - assets/audio/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon-adaptive-foreground.png"
