// image category list
final Map<String, List<String>> categorizedImages = {
  'Animals': [
    'assets/puzzle_images/image_categories/animals/blackbuck.jpg',
    'assets/puzzle_images/image_categories/animals/elephant.jpg',
    'assets/puzzle_images/image_categories/animals/cat.jpg',
    'assets/puzzle_images/image_categories/animals/dressed_cat.jpg',
    'assets/puzzle_images/image_categories/animals/eagle.jpg',
    'assets/puzzle_images/image_categories/animals/frog.jpg',
    'assets/puzzle_images/image_categories/animals/horses.jpg',
    'assets/puzzle_images/image_categories/animals/ostrich.jpg',
    'assets/puzzle_images/image_categories/animals/parrot.jpg',
    'assets/puzzle_images/image_categories/animals/peacock.jpg',
    'assets/puzzle_images/image_categories/animals/puppies.jpg',
    'assets/puzzle_images/image_categories/animals/tiger.jpg',
  ],
  'Anime': [
    'assets/puzzle_images/image_categories/anime_images/pirate_flag.jpg',
    'assets/puzzle_images/image_categories/anime_images/giyu_dslayer.jpg',
    'assets/puzzle_images/image_categories/anime_images/luffy.jpg',
    'assets/puzzle_images/image_categories/anime_images/nezuko_chan.jpg',
    'assets/puzzle_images/image_categories/anime_images/luffy_zoro.jpg',
    'assets/puzzle_images/image_categories/anime_images/rikochan.jpg',
    'assets/puzzle_images/image_categories/anime_images/saitama.jpg',
    'assets/puzzle_images/image_categories/anime_images/itachi.jpg',
    'assets/puzzle_images/image_categories/anime_images/sukuna.jpg',
    'assets/puzzle_images/image_categories/anime_images/hashira.jpg',
    'assets/puzzle_images/image_categories/anime_images/akatsuki.jpg',
    'assets/puzzle_images/image_categories/anime_images/tanjiro.jpg',
    'assets/puzzle_images/image_categories/anime_images/tanjiro_team.jpg',
  ],
  'Cartoon': [
    'assets/puzzle_images/image_categories/cartoon/bal_ganesh.jpg',
    'assets/puzzle_images/image_categories/cartoon/mickey_mouse.jpg',
    'assets/puzzle_images/image_categories/cartoon/doraemon.svg',
    'assets/puzzle_images/image_categories/cartoon/tom_and_jerry.jpg',
    'assets/puzzle_images/image_categories/cartoon/sinchan.jpg',
    'assets/puzzle_images/image_categories/cartoon/minions.jpg',
    'assets/puzzle_images/image_categories/cartoon/krishna.jpg',
    'assets/puzzle_images/image_categories/cartoon/motu_patlu.jpg',
    'assets/puzzle_images/image_categories/cartoon/oggy_and_cockroaches.jpg',
    'assets/puzzle_images/image_categories/cartoon/spiderman.jpg',
    'assets/puzzle_images/image_categories/cartoon/super_mario.png',
    'assets/puzzle_images/image_categories/cartoon/fox.jpg',
  ],
  // 'Illusion': [
  //   'assets/puzzle_images/image_categories/illusion/board_illusion.jpg',
  //   'assets/puzzle_images/image_categories/illusion/spinning_illusion.jpg',
  //   'assets/puzzle_images/image_categories/illusion/ladder_illusion.jpg',
  //   'assets/puzzle_images/image_categories/illusion/illusion_1.jpg',
  //   'assets/puzzle_images/image_categories/illusion/holi_colors_illusion.jpg',
  //   'assets/puzzle_images/image_categories/illusion/greek_abstraction_illusion.jpg',
  //   'assets/puzzle_images/image_categories/illusion/illusion_2.jpg',
  //   'assets/puzzle_images/image_categories/illusion/zebra_illusion.jpg',
  //   'assets/puzzle_images/image_categories/illusion/color_illusion.jpg',
  //   'assets/puzzle_images/image_categories/illusion/chain_illusion.jpg',
  //   'assets/puzzle_images/image_categories/illusion/illusion_3.jpg',
  //   'assets/puzzle_images/image_categories/illusion/square_illusion.jpg',
  // ],
  'Natural': [
    'assets/puzzle_images/image_categories/natural/himalayas.jpg',
    'assets/puzzle_images/image_categories/natural/morpunkh.jpg',
    'assets/puzzle_images/image_categories/natural/mountain.jpg',
    'assets/puzzle_images/image_categories/natural/pink_roses.jpg',
    'assets/puzzle_images/image_categories/natural/railway_line.jpg',
    'assets/puzzle_images/image_categories/natural/space_earth_photo.jpg',
    'assets/puzzle_images/image_categories/natural/sunset_bird.jpg',
    'assets/puzzle_images/image_categories/natural/sunset.jpg',
    'assets/puzzle_images/image_categories/natural/trees_1.jpg',
    'assets/puzzle_images/image_categories/natural/walking_bridge.jpg',
    'assets/puzzle_images/image_categories/natural/water_drop.jpg',
    'assets/puzzle_images/image_categories/natural/waterfall.jpg',
  ],
  'Monuments': [
    'assets/puzzle_images/image_categories/monuments/christ_the_redeemer.jpg',
    'assets/puzzle_images/image_categories/monuments/eiffel_tower.jpg',
    'assets/puzzle_images/image_categories/monuments/giza_pyramid.jpg',
    'assets/puzzle_images/image_categories/monuments/red_fort.jpg',
    'assets/puzzle_images/image_categories/monuments/taj_mahal.jpg',
    'assets/puzzle_images/image_categories/monuments/statue_of_unity.jpg',
    'assets/puzzle_images/image_categories/monuments/colosseum.jpg',
    'assets/puzzle_images/image_categories/monuments/minar.jpg',
  ],
  'Person': [
    'assets/puzzle_images/image_categories/person/minato.jpg',
    'assets/puzzle_images/image_categories/person/eye.jpg',
    'assets/puzzle_images/image_categories/person/black_panthar.jpg',
    'assets/puzzle_images/image_categories/person/jack_sparrow.jpg',
    'assets/puzzle_images/image_categories/person/skull_mask.jpg',
    'assets/puzzle_images/image_categories/person/squid_game_character.jpg',
  ],
  'Vehicles': [
    'assets/puzzle_images/image_categories/vehicles/transport_truck.jpg',
    'assets/puzzle_images/image_categories/vehicles/red_sakharam.jpg',
    'assets/puzzle_images/image_categories/vehicles/car.jpg',
    'assets/puzzle_images/image_categories/vehicles/jcb.png',
    'assets/puzzle_images/image_categories/vehicles/vintage_chervolat.jpg',
    'assets/puzzle_images/image_categories/vehicles/3mercides.jpg',
    'assets/puzzle_images/image_categories/vehicles/alfa_romeo.jpg',
    'assets/puzzle_images/image_categories/vehicles/ambesadar.jpg',
    'assets/puzzle_images/image_categories/vehicles/dkw.jpg',
    'assets/puzzle_images/image_categories/vehicles/open_mercides.jpg',
    'assets/puzzle_images/image_categories/vehicles/mercides_jeep.jpg',
    'assets/puzzle_images/image_categories/vehicles/old_mustang.png',
  ],
  'Fictional': [
    'assets/puzzle_images/image_categories/fictional/fictional_1.jpg',
    'assets/puzzle_images/image_categories/fictional/fictional_2.jpg',
    'assets/puzzle_images/image_categories/fictional/fictional_3.jpg',
    'assets/puzzle_images/image_categories/fictional/fictional_4.jpg',
    'assets/puzzle_images/image_categories/fictional/fictional_5.jpg',
    'assets/puzzle_images/image_categories/fictional/fictional_6.jpg',
    'assets/puzzle_images/image_categories/fictional/fictional_7.jpg',
    'assets/puzzle_images/image_categories/fictional/fictional_8.jpg',
    'assets/puzzle_images/image_categories/fictional/fictional_9.jpg',
    'assets/puzzle_images/image_categories/fictional/fictional_11.jpg',
    'assets/puzzle_images/image_categories/fictional/fictional_12.jpg',
  ],
};

// difficulty indexes
final List<Map<String, int>> difficulties = [
  {'rows': 2, 'cols': 2},
  {'rows': 4, 'cols': 4},
  {'rows': 5, 'cols': 5},
  {'rows': 6, 'cols': 6},
  {'rows': 7, 'cols': 7},
  {'rows': 8, 'cols': 8},
  {'rows': 9, 'cols': 9},
  {'rows': 10, 'cols': 10},
  // {'rows': 0, 'cols': 0},
];

// difficulty names
final List<String> difficultyNames = [
  '4\npieces',
  '16\npieces',
  '25\npieces',
  '36\npieces',
  '49\npieces',
  '64\npieces',
  '81\npieces',
  '100\npieces',
  // 'ChoicePuzzle',
];

final Map<String, int> categoryProgress = {
  'Animals': 0,
  'Anime': 0,
  'Cartoon': 0,
  'Illusion': 0,
  'Natural': 0,
  'Monuments': 0,
  'Person': 0,
  'Vehicles': 0,
};

enum SnackBarStatus { OPENED, CLOSED, DISMISSED, SHOWING }
